### ISSUE TITLE
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugMainManifest'

### ISSUE THREAD

**Issue by pdalex** [labibramadhan/cordova-sunmi-inner-printer#29]
Hello!

do you still support this plugin?
does it work on v2?
can't run :(

<img width="1265" alt="image" src="https://github.com/labibramadhan/cordova-sunmi-inner-printer/assets/43449105/106b3fd2-f63f-49a0-b5ed-1807dd5b09a7">

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugMainManifest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)

**Comment by labibramadhan** [comment]
Sorry can't support anymore due to it's been so long ago since i don't own the device anymore.
